### ISSUE TITLE
Country Hubs: Greece Event #15

### ISSUE THREAD

**Issue by ubani** [eucardano/operations-framework#57]

**Comment by SiagasKostas** [comment]
The team contains people with backgrounds in teaching, community management, research and content creation, so it is uniquely equipped to handle audiences with different backgrounds and levels of crypto knowledge! From a crypto newbie to a seasoned veteran, we can help the attendees deepen their understanding of Cardano fundamentals, as well as more advanced and nuanced topics.

The core of our schedule is listed bellow:

1. Sort introduction of the OdyC DAO (i.e. the organising team)
  a. Who are we?
  b. Why are we hosting this workshop?
  c. What is the ECC?
2. From Bitcoin to Cardano, the journey towards decentralisation of the previous decade. 
  a. What is the consensus problem?
  b. What is the permissionless consensus problem that the invention of Bitcoin solved?
  c. What are smart contracts (aka programmable money)?
  d. PoS vs PoW 
  e. Cardano fundamentals 
1. How can anybody use the Cardano network (i.e. newbie onboarding)
  a. What is a wallet and how do I create one?
  b. What is a seed phrase and why keeping it private is fundamental for security? 
  c. Web 3.0 vs traditional banking ( aka self custody).
  d. Collateral and Staking.
  e. Governance 
4. We are set to go? What can we do now?
  a. DEXs and DeFi.
    i. What is DeFi?
    ii. What is a DEX?
    iii. What are Cardano native tokens and what function do they fulfil?
  b. Cardano NFTS 
    i. What is an NFT?
    ii. What are some of their potential utilities?
    ii. Who can I get one from the secondary market?
5. Closing remarks.
  a. What did we learn today?
  b. How can we leverage the blockchain as a fundamental tool to improve decentralisation and fairness our everyday technological and financial needs.


  
Of course, as all live educational events should be, the above mentioned schedule is indicative of a standard workshop. Depending on the audience’s background and interests, the team can focus more on the appropriate sub sections. For example, for a mostly beginner audience, section 2 will be brief, and more time will be given on sections 3 and 4. On the other hand, if the audience consists of seasoned crypto users of other ecosystems, sections 2 and 5 will be emphasised more. 

Date and time 
15th of june 
start 09.00 a.m. 
close 15.00 p.m.
maximum of 20 persons


The workshop will be presented by 
@OdyC_DAO and @EuCardano members
@Varavas9
@Ajani_the_Great
@mdimis
@KostasSiagas (X- accounts)

**Comment by ubani** [comment]
Hey @SiagasKostas, 

Thank you so much for hosting!

Here is the requested feedback:

Our [Event params](https://github.com/eucardano/operations-framework/blob/main/countryhubs/event-params.md) provide some context to allow us to expand on our [Blueprints for founders and donations](https://github.com/eucardano/operations-framework/blob/main/blueprints/001-founders.md) to get more Q&A by the community. 

- [ ] It would be great to see some reference points of the Blueprint topics.
- [ ] This is a great outline and you are covering a lot within 6 hours. 
- [ ] Veteran could see this agenda as too general. 
- [ ] You are planning a series of events. 
- [ ] Consider to distribute your agenda over the series of events. 
- [ ] This would allow both newbies and veterans to evolve, share insights, grow together and cover the [blueprint topics ("founder, donations" - perspectives)](https://github.com/eucardano/operations-framework/blob/main/blueprints/001-founders.md)
- [ ] Potential typo in 4.ii `Who` -> `How`

**Comment by SiagasKostas** [comment]
Edit: New additions to the schedule are marked blue, and are in accordance with the founders section in ECC’s github.

[Odyc_Workshops_2.docx](https://github.com/eucardano/operations-framework/files/15380830/Odyc_Workshops_2.docx)

**Comment by ubani** [comment]
@SiagasKostas in our meeting today we confirmed, that if you are holding two workshops back to back with the same participants then these would also count as two workshops.
That means you have double budget but only one merch budget.

**Comment by SiagasKostas** [comment]
Thank you very much for the clarification but I cannot have the same people for the second day in a row learning about Cardano. Think about it, summer will have started and everyone prefers the beaches. They will get a knowledge packet picked up and if we see interest we will deepen it by renewing the appointment for another day at a distance of at least a month. In this case we will let you know that we don't need merchandise because we will have an expression of interest form showing if someone attends a second time. The form will be open so you can see the participants.

**Comment by SiagasKostas** [comment]
There is always the thought that we can break the course into two parts, provided that we give the trainees time. We could, for example, leave part 4 ( in the new version of doc I send u) for deepening in the next workshop. This means that we would need merchandise for 40 people for the first and second event and not for the third and fourth. This can of course be changed if we see through the expression of interest form that the demand is high. Finally we can also drop the number of participants to 15 per workshop and of course the merchandise will go to the next students or can be returned.

**Comment by ubani** [comment]
> Edit: New additions to the schedule are marked blue, and are in accordance with the founders section in ECC’s github.
> 
> [Odyc_Workshops_2.docx](https://github.com/eucardano/operations-framework/files/15380830/Odyc_Workshops_2.docx)

We haven't said this before, but it is easier to follow up if you just create an md-file in our repo. https://github.com/eucardano/operations-framework/tree/main/countryhubs

Feel free to create a folder for Greece and create your documents in there.
If you're working directly in GitHub it would be done like so:

`...`->`create new file` -> `greece/yourfilename.md`

**Comment by ubani** [comment]
We would also need your introductionary text and banner for Twitter and our Discord event.

**Comment by SiagasKostas** [comment]
My friends, we have to add another workshop for the OdyC DAO team based in Thessaloniki, the second largest city in Greece. On June 21  and 19.00pm.  It will be presented by ,DAO members. For the workshop they will keep the same structure.

**Comment by SiagasKostas** [comment]
Hello friends, here is the banner for Athens and Thessaloniki. 

**Introduction**
We are OdyC DAO, a greek Cardano DAO oriented towards driving the adoption of our protocol in Greece and Cyprus. We wish to organise workshops across Greece, primarily in Athens and Thessaloniki (the two biggest urban centres of Greece, where most of our members are currently located). Our future plans include expanding our operations everywhere in Greece, including large rural areas. 

Due to the low level of crypto awareness in Greece, the main focus of our first workshops is to get as many people acquainted with the basic Cardano use cases, such as non custodial wallets, DeFi and NFTs. We will begin my aiming our efforts towards spreading Cardano awareness in key demographics, such as bankers, lawyers and accountants. Our events will be free to register (staying true to Cardano’s decentralized nature), so everyone will be welcomed!

We will begin hosting workshops mid-June, and according to the interest of the public, we will recalibrate from there! Our original idea is hosting 2 events at least once per month.

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


![2](https://github.com/eucardano/operations-framework/assets/165184558/e9792be3-cf98-4ddf-bbbf-592a921b4a70)

**Athens Schedule**
10:00 @homouniversalis_kostas :

- Who We Are

- ECC and Catalyst

11:00 @apocrypto:

- What is Decentralization 

- From Bitcoin to Cardano: The Journey Towards Decentralization

11:45 Break (20 minutes)

12:00 @tsoumas:

- The Consensus Problem

- What is a Wallet and How Do I Create One?

12:40 @cryptonea:

- NFTs

- Workshop Closing

13:00 Pizza and Open Discussion



----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



![1](https://github.com/eucardano/operations-framework/assets/165184558/28d181ac-b210-4bbe-a6d8-6f207688149e)
**Thessaloniki Schedule**

@pavlos201   15'
-Introduction to the workshop -> what is ECC, OdyC DAO, project Catalyst

@marialena_v  30'
-From Bitcoin to Eth and Cardano, the journey towards decentralisation

@cryptovag   55'
-what is a wallet and how do I create one and make a transaction
-DEX/DeFi/Web 3.0
-what are NFTs/mentioning some major Cardano native projects

@spartanjs  10'
-World Mobile project introduction

@apetr_8911  10'
-Palmyra project introduction

**Comment by SiagasKostas** [comment]
[Workshops June 2024.zip](https://github.com/user-attachments/files/15973192/Workshops.June.2024.zip)
let me know if is everything fine

**Comment by GeoTsoumas** [comment]
> > Edit: New additions to the schedule are marked blue, and are in accordance with the founders section in ECC’s github.
> > [Odyc_Workshops_2.docx](https://github.com/eucardano/operations-framework/files/15380830/Odyc_Workshops_2.docx)
> 
> We haven't said this before, but it is easier to follow up if you just create an md-file in our repo. https://github.com/eucardano/operations-framework/tree/main/countryhubs
> 
> Feel free to create a folder for Greece and create your documents in there. If you're working directly in GitHub it would be done like so:
> 
> `...`->`create new file` -> `greece/yourfilename.md`

Hello Marcus, I have taken our workshops' deliverables from Costas. I tried to follow your instructions here, but it seems I require access first. Can you please give it to me, so we can conclude this part of the process.  Thanks!

**Comment by ubani** [comment]
@GeoTsoumas 

### Adding new content
You can add new content (folders, files, images) by creating a fork.  
This will basically clone the repository into your own workspace.  
In there you can delete, edit, or add files. You can do that direct on GH if you don't like to download the repo or don't want to deal with the command line.  
For example create a folder by creating a new file in this format`foldername/filename.md`

After saving the file you can create a pull request (PR) and add a comment of what you have changed. The team will review and hopefully be able to merge the edits then.
Make sure to sync your fork before the PR.

Here is a little explainer video (series): https://www.youtube.com/watch?v=nT8KGYVurIU  

### Compensation
As for your question regarding the compensation follow this link: https://github.com/eucardano/operations-framework/blob/main/countryhubs/event-params.md  

From what I can see there are three workshops from OdyC DAO for ECC.  
With that you can tripple the budget per workshop and provide receipts accordingly.  
If you have provided merch by yourself - as you have done - then we can reimburse your design time and print expenses. Note for this you have to open source your designs including the working files and ECC and our logo need to be prominent on it. Upload the files in a new folder (e.g. `OdyC DAO or Greece`) here: https://github.com/eucardano/brandassets/tree/main/merch2024

**Comment by GeoTsoumas** [comment]
Hello Marcus, you will find attached here OdyC DAO's expense report. Due to an very urgent (and unexpected) work related issue, I don't have the time right now to create the GH repo you requested. Please check the report so our members can be reimbursed for their expenses. Thank you for your help. 
[OdyC DAO workshop expenses report.pdf](https://github.com/user-attachments/files/16179839/OdyC.DAO.workshop.expenses.report.pdf)

**Comment by ubani** [comment]
@GeoTsoumas can you please upload the PDF again. 
It doesn't resolve right now.

**Comment by GeoTsoumas** [comment]
[OdyC DAO workshop expenses report.pdf](https://github.com/user-attachments/files/16198761/OdyC.DAO.workshop.expenses.report.pdf)

**Comment by ubani** [comment]
Thank you @GeoTsoumas I do not see totals in the table.
So just to confirm, the table is our reference point, correct? 

Good formatting and sums are always a good way to ease the process. 
( i.e. use the same format of digits, prefer right alignment for numbers and left alignment for text, finalize with sums)

**Comment by GeoTsoumas** [comment]
Yes this is the final amounts. There are two tables, one for ADA rewards and one for expenses in euros. Also, keep in mind the 113 ADA in total we gave the participants, as displayed in the last page. I will keep the format you suggested in mind and incorporate in the process moving forward.

**Comment by ubani** [comment]
Please add your results document from the Country Hubs workshops (CHWS)for our founders' blueprints here, too.

**Comment by GeoTsoumas** [comment]
Here is the finalized version of the expense report
[OdyC_DAO_workshop_expenses_report.pdf](https://github.com/user-attachments/files/16202374/OdyC_DAO_workshop_expenses_report.pdf)

**Comment by GeoTsoumas** [comment]
Regarding the the results document, please specify the format requirements of the document here, if there are any.

**Comment by ubani** [comment]
> Here is the finalized version of the expense report [OdyC_DAO_workshop_expenses_report.pdf](https://github.com/user-attachments/files/16202374/OdyC_DAO_workshop_expenses_report.pdf)

Great, this makes it so much easier.

To make things even more obvious, 
- separate by topics by host, catering, venue, merch
- Use the receipts in the same order as in the table.
- add a grand total

The amounts given in the table are not entirely correct: 

- 17/6 `18,00 -> 17,97` Consumables for Thessaloniki's workshop 
- 18/6 ` 8,00 ->  8,07` Laser pointer for Thessaloniki's workshop presentations 
- Total `842,34 -> 842,38` for expenses

**Comment by GeoTsoumas** [comment]
Here is the finale version of the expense report, the rounding up errors have been adjusted to match the amounts listed in the receipts with cents precision. The order of the receipts listed is the same as the order of the expenses table. 
[Finale OdyC DAO workshop expenses report.pdf](https://github.com/user-attachments/files/16216346/Finale.OdyC.DAO.workshop.expenses.report.pdf)

**Comment by GeoTsoumas** [comment]
Here is the GitHub link to the results documents, as requested https://github.com/eucardano/operations-framework/issues/89#issuecomment-2227308318

**Comment by ubani** [comment]
@GeoTsoumas Thanks! 
Your total was still of 0,04 € short, I am correcting this in the transaction.  
The current rate of 0,39 € converts `842,38 € -> 2.159,85 ADA`

Resulting in: 
```
1.200,00 Host
2.159,85 Venue, catering 
  113,00 ADA Distribution
=================
3.472,85 ADA Grand total 
```

Here is the proof of Transaction: https://app.summonplatform.io/multisig/470aa3c3-664f-4e0d-b252-033aba13d3c3/b8558f09-5bd7-49a5-9a27-c53f2cc3b5c4
